# Generated by Django 5.2.5 on 2025-08-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_amount"),
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-id"], "verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lesson",
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="materials.course"
            ),
        ),
    ]
