# Generated by Django 5.2.5 on 2025-08-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_options_remove_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите ID сессии", max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
