# Generated by Django 5.2.5 on 2025-08-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default="2025-08-23 14:05:21.678045+03"),
            preserve_default=False,
        ),
    ]
